stages:
  - check

variables:
  IMAGE: nixos/nix # Use the official Nix Docker image

flake_check:
  stage: check
  image: $IMAGE
  script:
    - echo "Checking the flake"
    - nix flake check --extra-experimental-features nix-command --extra-experimental-features flakes
    - echo "Flake check completed"
