services:
  atuin:
    container_name: atuin
    restart: always
    image: ghcr.io/atuinsh/atuin
    command: server start
    depends_on:
      - atuin-db
    networks:
      - atuin-internal
      - atuin-external
    volumes:
      - /ssd/critical/atuin/config:/config
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - /ssd/critical/atuin/secrets.env
    environment:
      ATUIN_HOST: 0.0.0.0
      ATUIN_OPEN_REGISTRATION: false
      RUST_LOG: info,atuin_server=debug
    labels:
      traefik.enable: true
      traefik.docker.network: atuin
      traefik.http.routers.atuin.rule: Host(`atuin.dominik-schwaiger.ch`)
      traefik.http.routers.atuin.tls: true
      traefik.http.routers.atuin.tls.certresolver: letsencrypt
      traefik.http.services.atuin.loadbalancer.server.port: 8888

  atuin-db:
    image: pgautoupgrade/pgautoupgrade:alpine
    container_name: atuin-database
    restart: always
    env_file:
      - /ssd/critical/atuin/secrets.env
    networks:
      - atuin-internal
    volumes:
      - /ssd/critical/atuin/database:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      POSTGRES_USER: atuin
      POSTGRES_DB: atuin

networks:
  atuin-internal:

  atuin-external:
    name: atuin
    external: true
