services:
  stalwart:
    image: stalwartlabs/stalwart:v0.16.6
    container_name: stalwart
    ports:
      - 25:25 # SMTP  (explicit TLS => STARTTLS, Authentication is DISABLED => use port 465/587 instead)
      - 143:143 # IMAP4 (explicit TLS => STARTTLS)
      - 465:465 # ESMTP (implicit TLS)
      - 587:587 # ESMTP (explicit TLS => STARTTLS)
      - 993:993 # IMAP4 (implicit TLS)
      - 4190:4190 # ManageSieve (Sieve scripts)
    networks:
      - stalwart
    restart: always
    volumes:
      - /ssd/critical/stalwart/etc:/etc/stalwart
      - /ssd/critical/stalwart/data:/var/lib/stalwart
      - /etc/localtime:/etc/localtime:ro
    environment:
      STALWART_PUBLIC_URL: https://mail.dominik-schwaiger.ch
    labels:
      traefik.enable: true
      traefik.docker.network: stalwart
      traefik.tcp.routers.stalwart.rule: HostSNI(`mail.dominik-schwaiger.ch`) || HostSNI(`autodiscover.dominik-schwaiger.ch`) || HostSNI(`autoconfig.dominik-schwaiger.ch`) || HostSNI(`smtp.dominik-schwaiger.ch`) || HostSNI(`imap.dominik-schwaiger.ch`) || HostSNI(`mta-sts.dominik-schwaiger.ch`)
      traefik.tcp.routers.stalwart.entrypoints: websecure
      traefik.tcp.routers.stalwart.tls.passthrough: true
      traefik.tcp.services.stalwart.loadbalancer.server.port: 443

  stalwart-old:
    image: stalwartlabs/stalwart:v0.15.5
    container_name: stalwart-old
    networks:
      - stalwart
    restart: always
    volumes:
      - /ssd/critical/stalwart/old:/opt/stalwart
      - /etc/localtime:/etc/localtime:ro
      - certs:/data/certs:ro # certs from traefik
    labels:
      traefik.enable: true
      traefik.docker.network: stalwart
      traefik.http.routers.stalwart-old.rule: Host(`stalwart-old.dominik-schwaiger.ch`)
      traefik.http.routers.stalwart-old.tls: true
      traefik.http.routers.stalwart-old.tls.certresolver: letsencrypt
      traefik.http.services.stalwart-old.loadbalancer.server.port: 8080

volumes:
  certs:
    name: traefik_certs
    external: true

networks:
  stalwart:
    name: stalwart
    external: true
