services:
  prometheus:
    image: prom/prometheus:v3.3.1
    container_name: prometheus
    restart: always
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=30d
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - /hdd/non-critical/prometheus:/prometheus
      - /etc/localtime:/etc/localtime:ro
    networks:
      - monitoring-internal
      - monitoring-external
    labels:
      traefik.enable: true
      traefik.docker.network: monitoring
      traefik.http.routers.prometheus.rule: Host(`prometheus.dominik-schwaiger.ch`)
      traefik.http.routers.prometheus.tls: true
      traefik.http.routers.prometheus.tls.certresolver: letsencrypt
      traefik.http.routers.prometheus.middlewares: authentik@docker
      traefik.http.services.prometheus.loadbalancer.server.port: 9090

  grafana:
    image: grafana/grafana:13.0.1
    container_name: grafana
    restart: always
    depends_on:
      - prometheus
    volumes:
      - /ssd/critical/grafana:/var/lib/grafana
      - /etc/localtime:/etc/localtime:ro
    networks:
      - monitoring-internal
      - monitoring-external
    labels:
      traefik.enable: true
      traefik.docker.network: monitoring
      traefik.http.routers.grafana.rule: Host(`grafana.dominik-schwaiger.ch`)
      traefik.http.routers.grafana.tls: true
      traefik.http.routers.grafana.tls.certresolver: letsencrypt
      traefik.http.services.grafana.loadbalancer.server.port: 3000

  node-exporter:
    image: prom/node-exporter:v1.11.1
    container_name: node-exporter
    restart: always
    command:
      - --path.rootfs=/host
    pid: host
    network_mode: host
    volumes:
      - /:/host:ro,rslave
      - /etc/localtime:/etc/localtime:ro

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.56.2
    container_name: cadvisor
    restart: always
    privileged: true
    devices:
      - /dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /dev/disk:/dev/disk:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - monitoring-internal

networks:
  monitoring-internal:

  monitoring-external:
    name: monitoring
    external: true
