services:
  # TODO: enable metrics for: wg-easy(https://wg-easy.github.io/wg-easy/development/advanced/metrics/prometheus)
  prometheus:
    image: prom/prometheus:v3.12.0
    container_name: prometheus
    restart: always
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=30d
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - /ssd/critical/stalwart/metrics-password:/etc/prometheus/stalwart-password:ro
      - /hdd/non-critical/prometheus:/prometheus
      - /etc/localtime:/etc/localtime:ro
    networks:
      - monitoring-internal
      - monitoring-external
    labels:
      traefik.enable: true
      traefik.docker.network: monitoring
      traefik.http.routers.prometheus.rule: Host(`prometheus.dominik-schwaiger.ch`)
      traefik.http.routers.prometheus.tls: true
      traefik.http.routers.prometheus.tls.certresolver: letsencrypt
      traefik.http.routers.prometheus.middlewares: authentik@docker
      traefik.http.services.prometheus.loadbalancer.server.port: 9090

  grafana:
    image: grafana/grafana:13.0.1
    container_name: grafana
    restart: always
    depends_on:
      - prometheus
    env_file:
      - /ssd/critical/grafana/secrets.env
    environment:
      GF_AUTH_GENERIC_OAUTH_ENABLED: "true"
      GF_AUTH_GENERIC_OAUTH_NAME: "authentik"
      GF_AUTH_GENERIC_OAUTH_SCOPES: "openid profile email entitlements"
      GF_AUTH_GENERIC_OAUTH_AUTH_URL: "https://auth.dominik-schwaiger.ch/application/o/authorize/"
      GF_AUTH_GENERIC_OAUTH_TOKEN_URL: "https://auth.dominik-schwaiger.ch/application/o/token/"
      GF_AUTH_GENERIC_OAUTH_API_URL: "https://auth.dominik-schwaiger.ch/application/o/userinfo/"
      GF_AUTH_SIGNOUT_REDIRECT_URL: "https://auth.dominik-schwaiger.ch/application/o/grafana/end-session/"
      # Optionally enable auto-login (bypasses Grafana login screen)
      GF_AUTH_OAUTH_AUTO_LOGIN: "true"
      # Optionally map user entitlements to Grafana roles
      GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: "contains(entitlements[*], 'Grafana Admins') && 'Admin' || contains(entitlements[*], 'Grafana Editors') && 'Editor' || 'Viewer'"
      # Required if Grafana is running behind a reverse proxy
      GF_SERVER_ROOT_URL: "https://grafana.dominik-schwaiger.ch"
      # Required to allow OAuth to assign the server-wide GrafanaAdmin role
      GF_AUTH_GENERIC_OAUTH_ALLOW_ASSIGN_GRAFANA_ADMIN: "true"
      GF_SMTP_ENABLED: "true"
      GF_SMTP_HOST: "mail.dominik-schwaiger.ch:587"
      GF_SMTP_USER: "grafana@dominik-schwaiger.ch"
      GF_SMTP_FROM_ADDRESS: "grafana@dominik-schwaiger.ch"
    volumes:
      - /ssd/critical/grafana:/var/lib/grafana
      - /etc/localtime:/etc/localtime:ro
    networks:
      - monitoring-internal
      - monitoring-external
    labels:
      traefik.enable: true
      traefik.docker.network: monitoring
      traefik.http.routers.grafana.rule: Host(`grafana.dominik-schwaiger.ch`)
      traefik.http.routers.grafana.tls: true
      traefik.http.routers.grafana.tls.certresolver: letsencrypt
      traefik.http.services.grafana.loadbalancer.server.port: 3000

  node-exporter:
    image: prom/node-exporter:v1.11.1
    container_name: node-exporter
    restart: always
    command:
      - --path.rootfs=/host
      - --collector.zfs
      - --collector.systemd
    pid: host
    networks:
      - monitoring-internal
    volumes:
      - /:/host:ro,rslave
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket:ro
      - /etc/localtime:/etc/localtime:ro

  cadvisor:
    image: ghcr.io/google/cadvisor:0.57
    container_name: cadvisor
    restart: always
    privileged: true
    devices:
      - /dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /dev/disk:/dev/disk:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - monitoring-internal

networks:
  monitoring-internal:

  monitoring-external:
    name: monitoring
    external: true
