log:
  level: "INFO"

api:
  dashboard: true

providers:
  docker:
    exposedByDefault: false

global:
  sendAnonymousUsage: true

entryPoints:
  metrics:
    address: ":8082"

  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "websecure"
          scheme: "https"
    transport:
      respondingTimeouts:
        readTimeout: "15m"
        writeTimeout: "15m"
        idleTimeout: "15m"

  websecure:
    address: ":443"
    transport:
      respondingTimeouts:
        readTimeout: "60m"
        writeTimeout: "60m"
        idleTimeout: "15m"

metrics:
  prometheus:
    entryPoint: metrics

certificatesResolvers:
  letsencrypt:
    acme:
      email: "mail@dominik-schwaiger.ch"
      storage: "/etc/certs/acme.json"
      propagation:
        delayBeforeChecks: 30s
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
