services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:15
    container_name: wg-easy
    environment:
      INSECURE: true
    networks:
      wg-easy:
      wg:
        ipv4_address: 10.42.42.42
        ipv6_address: fdcc:ad94:bacf:61a3::2a
    ports:
      - 51820:51820/udp
    restart: always
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      net.ipv4.ip_forward: 1
      net.ipv4.conf.all.src_valid_mark: 1
      net.ipv6.conf.all.disable_ipv6: 0
      net.ipv6.conf.all.forwarding: 1
      net.ipv6.conf.default.forwarding: 1
    volumes:
      - /ssd/critical/wg-easy:/etc/wireguard
      - /etc/localtime:/etc/localtime:ro
    labels:
      traefik.enable: true
      traefik.docker.network: wg-easy
      traefik.http.routers.wg-easy.rule: Host(`vpn.dominik-schwaiger.ch`)
      traefik.http.routers.wg-easy.tls: true
      traefik.http.routers.wg-easy.tls.certresolver: letsencrypt
      traefik.http.services.wg-easy.loadbalancer.server.port: 51821
      traefik.http.routers.wg-easy.middlewares: authentik@docker

networks:
  wg-easy:
    name: wg-easy
    external: true

  wg:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 10.42.42.0/24
        - subnet: fdcc:ad94:bacf:61a3::/64
